### ISSUE TITLE
the content in "here" is missing

### ISSUE THREAD

**Issue by cristiano2333** [zef1611/AIC23_NLRetrieval_HCMIU_CVIP#1]
google 404

**Comment by cristiano2333** [comment]
I'll be really appreciated if you can answer my doubts

**Comment by zef1611** [comment]
Hi, sorry for the late reply, I have been very busy lately so I cannot response anytime soon. The files in the google drive are deleted by my previous lab, however I no longer have access to that file either since I have left the lab. 

You can try to reproduce the model using the provided code from our repo, if possible I will try to train a new version and upload the weights.

Thank you for taking a big interested in our solution, hope you have a nice day.
