### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by sanazkhalili** [zef1611/AIC23_NLRetrieval_HCMIU_CVIP#3]
Hello,
I can't download checkpoints.  I'm encountering a 404 error.

**Comment by zef1611** [comment]
Hi, the files in the google drive are deleted by my previous lab, however I no longer have access to that file either since I have left the lab.

You can try to reproduce the model using the provided code from our repo, if possible I will try to train a new version and upload the weights.

Thank you for taking a big interested in our solution, hope you have a nice day.

**Comment by rishabh-akridata** [comment]
@zef1611 Nice, work. I also want the checkpoints. Did you get a chance to train a new version ?
